# Generated by Django 2.2.6 on 2019-11-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auth0user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.CharField(default='dummy', max_length=200),
            preserve_default=False,
        ),
    ]
